kind: pipeline
name: build
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build-master
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      dockerfile: Dockerfile
      tag:
        - ${DRONE_BRANCH}
      username:
        from_secret: global_docker_login
      password:
        from_secret: global_docker_password
      registry:
        from_secret: global_docker_registry
      repo:
        from_secret: docker_repo
